CROPS = [
    {
        "id": "aceitunas",
        "rcr": 0.80,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "ajo",
        "rcr": 0.30,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "alcachofa",
        "rcr": 1.50,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "albaricoques",
        "rcr": 0.60,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "alfalfa",
        "rcr": 0.10,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "algodón",
        "rcr": 2.50,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "algodon",
        "rcr": 2.50,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "almendras",
        "rcr": 1.20,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "anís",
        "rcr": 1.00,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "anis",
        "rcr": 1.00,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "apio",
        "rcr": 0.30,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "arroz",
        "rcr": 1.40,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "banana",
        "rcr": 2.00,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "batata",
        "rcr": 0.40,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "berenjena",
        "rcr": 0.60,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "brócoli",
        "rcr": 1.20,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "brocoli",
        "rcr": 1.20,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "cacao",
        "rcr": 1.10,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "café",
        "rcr": 0.85,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "cafe",
        "rcr": 0.85,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "calabacín",
        "rcr": 0.60,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "calabacin",
        "rcr": 0.60,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "calabaza",
        "rcr": 0.60,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "caña de azúcar",
        "rcr": 0.30,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "cana de azucar",
        "rcr": 0.30,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "cebada/avena",
        "rcr": 1.20,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "cebolla",
        "rcr": 0.30,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "cebollín",
        "rcr": 0.20,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "cebollin",
        "rcr": 0.20,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "céleri",
        "rcr": 0.30,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "celeri",
        "rcr": 0.30,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "cilantro",
        "rcr": 0.20,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "cítricos",
        "rcr": 0.70,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "citricos",
        "rcr": 0.70,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "coliflor",
        "rcr": 1.20,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "durazno",
        "rcr": 0.60,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "espárragos",
        "rcr": 1.50,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "esparragos",
        "rcr": 1.50,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "espinaca",
        "rcr": 0.20,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "forestal",
        "rcr": 1.00,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "fresa",
        "rcr": 0.30,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "girasol",
        "rcr": 2.00,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "guisantes o arveja (semillas)",
        "rcr": 1.20,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "guisantes o arveja",
        "rcr": 1.20,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "frijoles verdes",
        "rcr": 1.00,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "frijoles",
        "rcr": 1.15,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "lechuga",
        "rcr": 0.20,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "lentejas",
        "rcr": 1.15,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "maíz (grano)",
        "rcr": 1.20,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "maiz (grano)",
        "rcr": 1.20,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "maíz",
        "rcr": 1.20,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "maiz",
        "rcr": 1.20,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "manzana",
        "rcr": 0.60,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "melón",
        "rcr": 0.50,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "melon",
        "rcr": 0.50,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "moringa",
        "rcr": 1.00,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "nueces",
        "rcr": 1.10,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "olivos",
        "rcr": 0.80,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "palma",
        "rcr": 1.50,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "pasto",
        "rcr": 0.10,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "patata o papa",
        "rcr": 0.40,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "pepino",
        "rcr": 0.60,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "piña",
        "rcr": 1.50,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "pina",
        "rcr": 1.50,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "pistachos",
        "rcr": 1.10,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "plátano",
        "rcr": 2.00,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "platano",
        "rcr": 2.00,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "rábano",
        "rcr": 0.30,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "rabano",
        "rcr": 0.30,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "remolacha",
        "rcr": 0.30,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "repollo",
        "rcr": 1.20,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "ricino",
        "rcr": 1.50,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "sandía",
        "rcr": 0.50,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "sandia",
        "rcr": 0.50,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "sésamo",
        "rcr": 1.50,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "sesamo",
        "rcr": 1.50,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "sorgo (dulce)",
        "rcr": 1.30,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "sorgo",
        "rcr": 1.30,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "soya o soja",
        "rcr": 1.50,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "tomate",
        "rcr": 0.60,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "trigo (invierno)",
        "rcr": 1.30,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "trigo",
        "rcr": 1.30,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "uvas",
        "rcr": 0.80,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "yuca",
        "rcr": 0.40,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
    {
        "id": "zanahoria",
        "rcr": 0.30,
        "humidity_ratio": 0.50,
        "pyrolysis_yield": 0.30,
        "removal_factor": 2.5,
    },
]
